version: '3'
services:
  oracle_service:   
    container_name: oracle 
    image: jaspeen/oracle-xe-11g  
    volumes:
      - type: bind
        source: /home/ubuntu/oracle
        target: /u01/app/oracle
    ports:
      - 1521:1521  
    networks: 
      - test2
       
  web_service:
    container_name: web
    image: siyeonkim/security
    ports:
      - 9400:9400
    environment:
      spring.datasource.url: jdbc:oracle:thin:@oracle:1521/xe
      spring.datasource.hikari.data-source-properties.oracle.jdbc.timezoneAsRegion: 0
      my.sendfile: /home/ubuntu/download/cook1.png
    networks: 
       test2:
    volumes:
      - type: bind
      - source: /home/ubuntu/download/upload
      - target: /home/ubuntu/download/upload/
    depends_on:
     - oracle_service
   
networks: 
  test2:
